config/routes.rb
Rails.application.routes.draw do
  resources :labels

  resources :answers

  get 'answers/index'

  get 'answers/new'

  get 'answers/create'

  get 'answers/edit'

  get 'answers/destroy'

  get 'answers/show'

  get 'sessions/new'

  resources :users
  resources :questions
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy', via: 'delete'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/label.rb
class Label < ActiveRecord::Base
  has_and_belongs_to_many :questions
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]
  before_action :is_admin_user, only: [:show, :index]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id], )
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:title)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.erb
<%= form_for(@label) do |f| %>
  <% if @label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% @label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing label</h1>

<%= render 'form' %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<h1>Listing labels</h1>

<table>
  <thead>
    <tr>
      <th>Title:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.title %></td>
        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Label', new_label_path %>

app/views/labels/new.html.erb
<h1>New label</h1>

<%= render 'form' %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p id="notice"><%= notice %></p>
<p>Title: <%= @label.title %></p>
<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>