config/routes.rb
Rails.application.routes.draw do
  resources :labels

  resources :answers

  get 'answers/index'

  get 'answers/new'

  get 'answers/create'

  get 'answers/edit'

  get 'answers/destroy'

  get 'answers/show'

  get 'sessions/new'

  resources :users
  resources :questions
  resources :sessions, only: [:new, :create, :destroy]

  root 'home#index'

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy', via: 'delete'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_admin_panel.html.erb
<h3>Admin panel</h3>

<%= link_to "Users", users_path %><br/>
<%= link_to "Questions", questions_path %><br/>
<%= link_to "Answers", answers_path %><br/>
<%= link_to "Labels", labels_path %><br/>


app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Asq question!", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
      <% unless signed_in? %>
        <li><%= link_to "Registration", signup_path %></li>
        <li><%= link_to "Login", signin_path %></li>
      <% else %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Signout", signout_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AsqQuestion</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">
  <div claas="row">
  	<div class="col-md-8">
      <%= yield %>
     </div>
    <div class="col-md-2">
      <%= render "layouts/admin_panel" if is_admin? %>
   	</div>
   </div>
</div>
</body>
</html>